import React from "react";
import Image from "next/image";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "",
  description: "",
};
const BlogDetails = () => {
  const article = {
    date: "2024-06-03",
    title: "CAPEX Solar Projects: Empowering Manufacturing Businesses",
    topicHeading: "What is the CAPEX Model?",
    topicDesc:
      "In the CAPEX (Capital Expenditure) model for solar installations, the consumer pays the total upfront cost for the solar system. This ownership grants access to tax benefits and depreciation advantages. While the initial investment is higher, energy savings allow consumers to recover it within 5-6 years. In contrast, the *OPEX* (Operational Expenditure) model shifts responsibility to a third party, who sets up and maintains the solar plant. Consumers pay only for the electricity, enjoying risk-free power at negotiated tariffs. After the agreed tenure, ownership of the solar plant transfers to the consumer at no additional cost. 🌞🔆",
    imageUrl:
      "/blogs/capex-solar-projects-empowering-manufacturing-businesses.jpg",
    sectionHeading:
      "The CAPEX Solar Model: Empowering Ownership and Efficiency",
    section1: [
      {
        heading: "Long-Term Cost Savings",
        title:
          "The CAPEX model offers manufacturing businesses a pathway to substantial long-term cost savings. By investing upfront in solar panels and related infrastructure, companies can eliminate monthly electricity bills. Moreover, surplus energy generated by the solar system can be sold back to the grid, creating an additional revenue stream.",
      },
      {
        heading: "Complete Ownership and Tax Benefits",
        title:
          "With CAPEX, businesses own the solar asset outright. This ownership comes with several advantages: \n\nTax Benefits: Commercial and industrial solar installations can avail up to 40% accelerated depreciation on their solar plants. CAPEX installations allow businesses to take advantage of such tax benefits, which the OPEX (Operational Expenditure) model does not offer. \n\nGovernment Subsidies and Rebates: Owning the solar system enables businesses to access government subsidies and rebates, further enhancing the financial viability of the investment.",
      },
      {
        heading: "Faster Return on Investment (ROI)",
        title:
          "The payback period for CAPEX solar projects is typically shorter than that of OPEX models. In many cases, businesses can recoup their initial investment within four years or less. This faster ROI ensures that the financial benefits of going solar are realised sooner.",
      },
      {
        heading: "Energy Independence and Stability",
        title:
          "Manufacturing businesses face fluctuating energy costs due to market dynamics and geopolitical factors. By generating their own solar power, companies reduce dependence on external energy sources. This energy independence provides stability and predictability in cost management.",
      },
      {
        heading:
          "Environmental Impact and Corporate Social Responsibility (CSR)",
        title:
          "Investing in CAPEX solar projects aligns with sustainability goals. By reducing reliance on fossil fuels, businesses contribute to environmental conservation and lower carbon emissions. Demonstrating commitment to CSR enhances the company’s reputation and resonates positively with stakeholders.",
      },
      {
        heading: "Utilisation of Rooftop Space",
        title:
          "CAPEX rooftop solar systems effectively utilize otherwise empty rooftop areas. By turning rooftops into productive assets that generate clean energy, businesses optimize space usage and contribute to a greener future.",
      },
      {
        heading: "Protection Against Rising Electricity Tariffs",
        title:
          "Electricity prices tend to rise over time. By owning the solar system, manufacturing businesses shield themselves from future tariff hikes. The fixed cost of solar energy ensures budget predictability for at least 25 years, providing a strategic advantage in cost management.",
      },
    ],

    section2: [
      {
        heading: "Understanding the CAPEX Model role in Tax Benefits",
        description:
          "In the CAPEX model, the consumer bears the full capital expenditure for the solar energy system. While this initial investment can be substantial, it comes with several advantages:",
        content: [
          {
            subheading: "Depreciation Deductions",
            details: [
              "Depreciation allows businesses to recover the cost of their solar assets over time by accounting for wear and tear.",
              "The Modified Accelerated Cost Recovery System (MACRS) in the United States provides a favorable depreciation schedule for solar investments, typically over five years.",
              "Accelerated depreciation significantly reduces taxable income, resulting in lower tax liability.",
            ],
          },
          {
            subheading: "Investment Tax Credits (ITC)",
            details: [
              "The Investment Tax Credit (ITC) allows businesses to claim a percentage of the total solar installation cost as a tax credit.",
              "Currently, the ITC offers a 26% credit on the total system cost for commercial solar projects.",
              "This credit directly reduces the business's tax burden, making solar investments more financially attractive.",
            ],
          },
          {
            subheading: "Bonus Depreciation",
            details: [
              "Bonus depreciation allows businesses to deduct a substantial portion of the solar investment cost in the first year.",
              "The Tax Cuts and Jobs Act (TCJA) permits 100% bonus depreciation for qualified property, including solar assets.",
              "Combining bonus depreciation with regular depreciation maximizes tax benefits and accelerates cost recovery.",
            ],
          },
          {
            subheading: "State and Local Incentives",
            details: [
              "Many states offer additional incentives to promote solar adoption, including grants, rebates, or tax credits.",
              "Research local programs to identify specific incentives available in your area, further enhancing the financial viability of your solar investment.",
            ],
          },
        ],
      },
    ],

    summary:
      "In summary, the CAPEX model empowers businesses to take ownership of their solar assets, enjoy tax benefits, achieve faster ROI, and contribute to environmental sustainability. As manufacturing companies increasingly prioritize efficiency and sustainability, CAPEX solar installations emerge as a smart investment choice.",
    conclusion:
      "The CAPEX model empowers businesses to take ownership of their solar assets, enjoy tax benefits, and contribute to environmental sustainability. While the initial investment may seem daunting, the long-term savings and positive impact on the environment make it a smart choice. Remember that consulting with a tax professional or financial advisor is crucial to maximise the benefits based on your specific circumstances. Investing in solar isn't just about saving money; it's an investment in a cleaner, greener future. So, take advantage of the tax benefits, harness the power of the sun, and make a positive impact!",
  };
  metadata.title = article.title;
  metadata.description = article.topicDesc;
  return (
    <>
      <div className="px-4">
        <Image
          src={article.imageUrl}
          alt="logo"
          width={100}
          height={10}
          className="rounded-2xl w-full h-full"
        />
      </div>
      <div className="mx-auto max-w-screen-2xl px-4 py-8 sm:px-6 sm:py-12 lg:px-8">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
          <div>
            <div className="px-4 text-center">
              <hr className="w-full h-3 mx-auto bg-black border-0 rounded dark:bg-gray-700"></hr>
              <div className="flex flex-row items-center gap-10">
                <h1 className="display-4 text-gray-900 animated slideInDown">
                  {article.title}
                </h1>
              </div>
              <hr className="w-full h-3 mx-auto bg-black border-0 rounded dark:bg-gray-700"></hr>
            </div>
            <div className="text-xl">
              <time
                dateTime={article.date}
                className="flex items-center gap-2 px-10  uppercase text-gray-900"
              >
                <span>
                  {new Date(article.date).toLocaleString("default", {
                    month: "long",
                    day: "numeric",
                  })}
                  {","}
                </span>
                <span>{new Date(article.date).getFullYear()}</span>
              </time>
            </div>
            <div className="p-10 ">
              <div className="text-lg font-bold text-justify">
                {article.topicHeading}
              </div>
              <div className="text-md text-justify">{article.topicDesc}</div>
            </div>

            {/* <div className="flex items-center gap-2 px-10 mt-3 text-gray-900">
              <Image
                className="rounded-full w-12 h-12"
                src="/placeholder.jpg"
                alt="image"
                width={64}
                height={64}
              />

              <div className="ml-4">
                <h3 className="text-xl font-bold text-gray-900">John snow</h3>
                <p className="text-gray-600">Designation</p>
              </div>
            </div> */}
          </div>
          <div className="p-4">
            <h3 className="text-gray-900 animated slideInDown">
              {article.sectionHeading}
            </h3>
            <ol className="text-lg text-justify text-gray-900 list-decimal pl-5">
              {article.section1.map((section, index) => (
                <li key={index} className="mb-4">
                  <div className="font-bold">{section.heading}</div>
                  <div>{section.title}</div>
                </li>
              ))}
            </ol>
            <div className="text-lg text-justify">{article.summary}</div>

            <div>
              <h3 className="py-3 text-gray-900">
                {article.section2[0].heading}
              </h3>
              <p className="text-lg text-justify text-gray-900">
                {article.section2[0].description}
              </p>
              <ul className="text-lg text-justify text-gray-900 list-disc pl-5">
                {article.section2[0].content.map((item, index) => (
                  <li key={index}>
                    <div className="font-bold">{item.subheading}</div>
                    <ul className="list-disc pl-5">
                      {item.details.map((detail, idx) => (
                        <li key={idx}>{detail}</li>
                      ))}
                    </ul>
                  </li>
                ))}
              </ul>
            </div>
            <div className="text-lg text-justify">
              <div className="font-bold">Conclusion:</div>
              {article.conclusion}
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default BlogDetails;
